// Checklist de tópicos por matéria para o Mapa de Progresso
export const TOPICS: Record<string, string[]> = {
  Matemática: [
    "Funções do 2º Grau",
    "Trigonometria",
    "Geometria Plana",
    "Geometria Espacial",
    "Progressões (PA e PG)",
    "Probabilidade e Estatística",
    "Matrizes e Determinantes",
    "Sistemas Lineares",
    "Logaritmos",
    "Análise Combinatória",
  ],
  Português: [
    "Análise Sintática",
    "Figuras de Linguagem",
    "Interpretação de Texto",
    "Funções da Linguagem",
    "Concordância Verbal e Nominal",
    "Regência",
    "Pontuação",
    "Variação Linguística",
  ],
  Redação: [
    "Estrutura Dissertativa",
    "Introdução com Repertório",
    "Desenvolvimento e Argumentação",
    "Proposta de Intervenção",
    "Coesão e Coerência",
    "Competências do ENEM",
  ],
  História: [
    "Brasil Colônia",
    "Independência e Império",
    "República Velha",
    "Era Vargas",
    "Ditadura Militar",
    "Idade Média",
    "Revolução Francesa",
    "Guerras Mundiais",
    "Guerra Fria",
    "Globalização",
  ],
  Geografia: [
    "Climas e Biomas",
    "Urbanização",
    "Globalização",
    "Geopolítica",
    "Recursos Hídricos",
    "Demografia",
    "Indústria e Energia",
    "Cartografia",
  ],
  Física: [
    "Mecânica — Cinemática",
    "Mecânica — Dinâmica",
    "Termodinâmica",
    "Óptica",
    "Ondulatória",
    "Eletricidade",
    "Magnetismo",
    "Física Moderna",
  ],
  Química: [
    "Atomística",
    "Tabela Periódica",
    "Ligações Químicas",
    "Estequiometria",
    "Termoquímica",
    "Equilíbrio Químico",
    "Química Orgânica",
    "Eletroquímica",
  ],
  Biologia: [
    "Citologia",
    "Genética",
    "Evolução",
    "Ecologia",
    "Botânica",
    "Zoologia",
    "Fisiologia Humana",
    "Microbiologia",
  ],
  Inglês: [
    "Reading Comprehension",
    "Verb Tenses",
    "Modal Verbs",
    "Phrasal Verbs",
    "Vocabulary",
    "False Cognates",
  ],
  Filosofia: [
    "Filosofia Antiga",
    "Filosofia Medieval",
    "Racionalismo e Empirismo",
    "Iluminismo",
    "Filosofia Contemporânea",
    "Ética e Política",
  ],
  Sociologia: [
    "Pensadores Clássicos",
    "Estado e Sociedade",
    "Cultura e Identidade",
    "Movimentos Sociais",
    "Trabalho e Capitalismo",
    "Indústria Cultural",
  ],
};

export const SUBJECT_EMOJI: Record<string, string> = {
  Matemática: "📐",
  Português: "📖",
  Redação: "✍️",
  História: "🏛️",
  Geografia: "🌎",
  Física: "⚡",
  Química: "⚗️",
  Biologia: "🧬",
  Inglês: "🌐",
  Filosofia: "🧠",
  Sociologia: "👥",
};
