/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimerRouteImport } from './routes/timer'
import { Route as RevisaoRapidaRouteImport } from './routes/revisao-rapida'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RedacoesRouteImport } from './routes/redacoes'
import { Route as PerfilRouteImport } from './routes/perfil'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as GruposRouteImport } from './routes/grupos'
import { Route as EsqueciSenhaRouteImport } from './routes/esqueci-senha'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ComunidadeRouteImport } from './routes/comunidade'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as BibliotecaRouteImport } from './routes/biblioteca'
import { Route as AssinaturaRouteImport } from './routes/assinatura'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SimuladosIndexRouteImport } from './routes/simulados.index'
import { Route as RedacoesIndexRouteImport } from './routes/redacoes.index'
import { Route as FlashcardsIndexRouteImport } from './routes/flashcards.index'
import { Route as ConteudosIndexRouteImport } from './routes/conteudos.index'
import { Route as SimuladosIdRouteImport } from './routes/simulados.$id'
import { Route as RedacoesTemasRouteImport } from './routes/redacoes.temas'
import { Route as RedacoesMinhasRouteImport } from './routes/redacoes.minhas'
import { Route as RedacoesEscreverRouteImport } from './routes/redacoes.escrever'
import { Route as RedacoesIdRouteImport } from './routes/redacoes.$id'
import { Route as ConteudosIdRouteImport } from './routes/conteudos.$id'
import { Route as FlashcardsIdEstudarRouteImport } from './routes/flashcards.$id.estudar'

const TimerRoute = TimerRouteImport.update({
  id: '/timer',
  path: '/timer',
  getParentRoute: () => rootRouteImport,
} as any)
const RevisaoRapidaRoute = RevisaoRapidaRouteImport.update({
  id: '/revisao-rapida',
  path: '/revisao-rapida',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacoesRoute = RedacoesRouteImport.update({
  id: '/redacoes',
  path: '/redacoes',
  getParentRoute: () => rootRouteImport,
} as any)
const PerfilRoute = PerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const GruposRoute = GruposRouteImport.update({
  id: '/grupos',
  path: '/grupos',
  getParentRoute: () => rootRouteImport,
} as any)
const EsqueciSenhaRoute = EsqueciSenhaRouteImport.update({
  id: '/esqueci-senha',
  path: '/esqueci-senha',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ComunidadeRoute = ComunidadeRouteImport.update({
  id: '/comunidade',
  path: '/comunidade',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const BibliotecaRoute = BibliotecaRouteImport.update({
  id: '/biblioteca',
  path: '/biblioteca',
  getParentRoute: () => rootRouteImport,
} as any)
const AssinaturaRoute = AssinaturaRouteImport.update({
  id: '/assinatura',
  path: '/assinatura',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosIndexRoute = SimuladosIndexRouteImport.update({
  id: '/simulados/',
  path: '/simulados/',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacoesIndexRoute = RedacoesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RedacoesRoute,
} as any)
const FlashcardsIndexRoute = FlashcardsIndexRouteImport.update({
  id: '/flashcards/',
  path: '/flashcards/',
  getParentRoute: () => rootRouteImport,
} as any)
const ConteudosIndexRoute = ConteudosIndexRouteImport.update({
  id: '/conteudos/',
  path: '/conteudos/',
  getParentRoute: () => rootRouteImport,
} as any)
const SimuladosIdRoute = SimuladosIdRouteImport.update({
  id: '/simulados/$id',
  path: '/simulados/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const RedacoesTemasRoute = RedacoesTemasRouteImport.update({
  id: '/temas',
  path: '/temas',
  getParentRoute: () => RedacoesRoute,
} as any)
const RedacoesMinhasRoute = RedacoesMinhasRouteImport.update({
  id: '/minhas',
  path: '/minhas',
  getParentRoute: () => RedacoesRoute,
} as any)
const RedacoesEscreverRoute = RedacoesEscreverRouteImport.update({
  id: '/escrever',
  path: '/escrever',
  getParentRoute: () => RedacoesRoute,
} as any)
const RedacoesIdRoute = RedacoesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => RedacoesRoute,
} as any)
const ConteudosIdRoute = ConteudosIdRouteImport.update({
  id: '/conteudos/$id',
  path: '/conteudos/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const FlashcardsIdEstudarRoute = FlashcardsIdEstudarRouteImport.update({
  id: '/flashcards/$id/estudar',
  path: '/flashcards/$id/estudar',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/calendario': typeof CalendarioRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/redacoes': typeof RedacoesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/revisao-rapida': typeof RevisaoRapidaRoute
  '/timer': typeof TimerRoute
  '/conteudos/$id': typeof ConteudosIdRoute
  '/redacoes/$id': typeof RedacoesIdRoute
  '/redacoes/escrever': typeof RedacoesEscreverRoute
  '/redacoes/minhas': typeof RedacoesMinhasRoute
  '/redacoes/temas': typeof RedacoesTemasRoute
  '/simulados/$id': typeof SimuladosIdRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/redacoes/': typeof RedacoesIndexRoute
  '/simulados/': typeof SimuladosIndexRoute
  '/flashcards/$id/estudar': typeof FlashcardsIdEstudarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/calendario': typeof CalendarioRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/reset-password': typeof ResetPasswordRoute
  '/revisao-rapida': typeof RevisaoRapidaRoute
  '/timer': typeof TimerRoute
  '/conteudos/$id': typeof ConteudosIdRoute
  '/redacoes/$id': typeof RedacoesIdRoute
  '/redacoes/escrever': typeof RedacoesEscreverRoute
  '/redacoes/minhas': typeof RedacoesMinhasRoute
  '/redacoes/temas': typeof RedacoesTemasRoute
  '/simulados/$id': typeof SimuladosIdRoute
  '/conteudos': typeof ConteudosIndexRoute
  '/flashcards': typeof FlashcardsIndexRoute
  '/redacoes': typeof RedacoesIndexRoute
  '/simulados': typeof SimuladosIndexRoute
  '/flashcards/$id/estudar': typeof FlashcardsIdEstudarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/assinatura': typeof AssinaturaRoute
  '/biblioteca': typeof BibliotecaRoute
  '/cadastro': typeof CadastroRoute
  '/calendario': typeof CalendarioRoute
  '/comunidade': typeof ComunidadeRoute
  '/dashboard': typeof DashboardRoute
  '/esqueci-senha': typeof EsqueciSenhaRoute
  '/grupos': typeof GruposRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/perfil': typeof PerfilRoute
  '/redacoes': typeof RedacoesRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/revisao-rapida': typeof RevisaoRapidaRoute
  '/timer': typeof TimerRoute
  '/conteudos/$id': typeof ConteudosIdRoute
  '/redacoes/$id': typeof RedacoesIdRoute
  '/redacoes/escrever': typeof RedacoesEscreverRoute
  '/redacoes/minhas': typeof RedacoesMinhasRoute
  '/redacoes/temas': typeof RedacoesTemasRoute
  '/simulados/$id': typeof SimuladosIdRoute
  '/conteudos/': typeof ConteudosIndexRoute
  '/flashcards/': typeof FlashcardsIndexRoute
  '/redacoes/': typeof RedacoesIndexRoute
  '/simulados/': typeof SimuladosIndexRoute
  '/flashcards/$id/estudar': typeof FlashcardsIdEstudarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/assinatura'
    | '/biblioteca'
    | '/cadastro'
    | '/calendario'
    | '/comunidade'
    | '/dashboard'
    | '/esqueci-senha'
    | '/grupos'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/redacoes'
    | '/reset-password'
    | '/revisao-rapida'
    | '/timer'
    | '/conteudos/$id'
    | '/redacoes/$id'
    | '/redacoes/escrever'
    | '/redacoes/minhas'
    | '/redacoes/temas'
    | '/simulados/$id'
    | '/conteudos/'
    | '/flashcards/'
    | '/redacoes/'
    | '/simulados/'
    | '/flashcards/$id/estudar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/assinatura'
    | '/biblioteca'
    | '/cadastro'
    | '/calendario'
    | '/comunidade'
    | '/dashboard'
    | '/esqueci-senha'
    | '/grupos'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/reset-password'
    | '/revisao-rapida'
    | '/timer'
    | '/conteudos/$id'
    | '/redacoes/$id'
    | '/redacoes/escrever'
    | '/redacoes/minhas'
    | '/redacoes/temas'
    | '/simulados/$id'
    | '/conteudos'
    | '/flashcards'
    | '/redacoes'
    | '/simulados'
    | '/flashcards/$id/estudar'
  id:
    | '__root__'
    | '/'
    | '/assinatura'
    | '/biblioteca'
    | '/cadastro'
    | '/calendario'
    | '/comunidade'
    | '/dashboard'
    | '/esqueci-senha'
    | '/grupos'
    | '/login'
    | '/onboarding'
    | '/perfil'
    | '/redacoes'
    | '/reset-password'
    | '/revisao-rapida'
    | '/timer'
    | '/conteudos/$id'
    | '/redacoes/$id'
    | '/redacoes/escrever'
    | '/redacoes/minhas'
    | '/redacoes/temas'
    | '/simulados/$id'
    | '/conteudos/'
    | '/flashcards/'
    | '/redacoes/'
    | '/simulados/'
    | '/flashcards/$id/estudar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AssinaturaRoute: typeof AssinaturaRoute
  BibliotecaRoute: typeof BibliotecaRoute
  CadastroRoute: typeof CadastroRoute
  CalendarioRoute: typeof CalendarioRoute
  ComunidadeRoute: typeof ComunidadeRoute
  DashboardRoute: typeof DashboardRoute
  EsqueciSenhaRoute: typeof EsqueciSenhaRoute
  GruposRoute: typeof GruposRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  PerfilRoute: typeof PerfilRoute
  RedacoesRoute: typeof RedacoesRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  RevisaoRapidaRoute: typeof RevisaoRapidaRoute
  TimerRoute: typeof TimerRoute
  ConteudosIdRoute: typeof ConteudosIdRoute
  SimuladosIdRoute: typeof SimuladosIdRoute
  ConteudosIndexRoute: typeof ConteudosIndexRoute
  FlashcardsIndexRoute: typeof FlashcardsIndexRoute
  SimuladosIndexRoute: typeof SimuladosIndexRoute
  FlashcardsIdEstudarRoute: typeof FlashcardsIdEstudarRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timer': {
      id: '/timer'
      path: '/timer'
      fullPath: '/timer'
      preLoaderRoute: typeof TimerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/revisao-rapida': {
      id: '/revisao-rapida'
      path: '/revisao-rapida'
      fullPath: '/revisao-rapida'
      preLoaderRoute: typeof RevisaoRapidaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacoes': {
      id: '/redacoes'
      path: '/redacoes'
      fullPath: '/redacoes'
      preLoaderRoute: typeof RedacoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perfil': {
      id: '/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof PerfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grupos': {
      id: '/grupos'
      path: '/grupos'
      fullPath: '/grupos'
      preLoaderRoute: typeof GruposRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/esqueci-senha': {
      id: '/esqueci-senha'
      path: '/esqueci-senha'
      fullPath: '/esqueci-senha'
      preLoaderRoute: typeof EsqueciSenhaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comunidade': {
      id: '/comunidade'
      path: '/comunidade'
      fullPath: '/comunidade'
      preLoaderRoute: typeof ComunidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/biblioteca': {
      id: '/biblioteca'
      path: '/biblioteca'
      fullPath: '/biblioteca'
      preLoaderRoute: typeof BibliotecaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assinatura': {
      id: '/assinatura'
      path: '/assinatura'
      fullPath: '/assinatura'
      preLoaderRoute: typeof AssinaturaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados/': {
      id: '/simulados/'
      path: '/simulados'
      fullPath: '/simulados/'
      preLoaderRoute: typeof SimuladosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacoes/': {
      id: '/redacoes/'
      path: '/'
      fullPath: '/redacoes/'
      preLoaderRoute: typeof RedacoesIndexRouteImport
      parentRoute: typeof RedacoesRoute
    }
    '/flashcards/': {
      id: '/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards/'
      preLoaderRoute: typeof FlashcardsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conteudos/': {
      id: '/conteudos/'
      path: '/conteudos'
      fullPath: '/conteudos/'
      preLoaderRoute: typeof ConteudosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulados/$id': {
      id: '/simulados/$id'
      path: '/simulados/$id'
      fullPath: '/simulados/$id'
      preLoaderRoute: typeof SimuladosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/redacoes/temas': {
      id: '/redacoes/temas'
      path: '/temas'
      fullPath: '/redacoes/temas'
      preLoaderRoute: typeof RedacoesTemasRouteImport
      parentRoute: typeof RedacoesRoute
    }
    '/redacoes/minhas': {
      id: '/redacoes/minhas'
      path: '/minhas'
      fullPath: '/redacoes/minhas'
      preLoaderRoute: typeof RedacoesMinhasRouteImport
      parentRoute: typeof RedacoesRoute
    }
    '/redacoes/escrever': {
      id: '/redacoes/escrever'
      path: '/escrever'
      fullPath: '/redacoes/escrever'
      preLoaderRoute: typeof RedacoesEscreverRouteImport
      parentRoute: typeof RedacoesRoute
    }
    '/redacoes/$id': {
      id: '/redacoes/$id'
      path: '/$id'
      fullPath: '/redacoes/$id'
      preLoaderRoute: typeof RedacoesIdRouteImport
      parentRoute: typeof RedacoesRoute
    }
    '/conteudos/$id': {
      id: '/conteudos/$id'
      path: '/conteudos/$id'
      fullPath: '/conteudos/$id'
      preLoaderRoute: typeof ConteudosIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/flashcards/$id/estudar': {
      id: '/flashcards/$id/estudar'
      path: '/flashcards/$id/estudar'
      fullPath: '/flashcards/$id/estudar'
      preLoaderRoute: typeof FlashcardsIdEstudarRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface RedacoesRouteChildren {
  RedacoesIdRoute: typeof RedacoesIdRoute
  RedacoesEscreverRoute: typeof RedacoesEscreverRoute
  RedacoesMinhasRoute: typeof RedacoesMinhasRoute
  RedacoesTemasRoute: typeof RedacoesTemasRoute
  RedacoesIndexRoute: typeof RedacoesIndexRoute
}

const RedacoesRouteChildren: RedacoesRouteChildren = {
  RedacoesIdRoute: RedacoesIdRoute,
  RedacoesEscreverRoute: RedacoesEscreverRoute,
  RedacoesMinhasRoute: RedacoesMinhasRoute,
  RedacoesTemasRoute: RedacoesTemasRoute,
  RedacoesIndexRoute: RedacoesIndexRoute,
}

const RedacoesRouteWithChildren = RedacoesRoute._addFileChildren(
  RedacoesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AssinaturaRoute: AssinaturaRoute,
  BibliotecaRoute: BibliotecaRoute,
  CadastroRoute: CadastroRoute,
  CalendarioRoute: CalendarioRoute,
  ComunidadeRoute: ComunidadeRoute,
  DashboardRoute: DashboardRoute,
  EsqueciSenhaRoute: EsqueciSenhaRoute,
  GruposRoute: GruposRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  PerfilRoute: PerfilRoute,
  RedacoesRoute: RedacoesRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  RevisaoRapidaRoute: RevisaoRapidaRoute,
  TimerRoute: TimerRoute,
  ConteudosIdRoute: ConteudosIdRoute,
  SimuladosIdRoute: SimuladosIdRoute,
  ConteudosIndexRoute: ConteudosIndexRoute,
  FlashcardsIndexRoute: FlashcardsIndexRoute,
  SimuladosIndexRoute: SimuladosIndexRoute,
  FlashcardsIdEstudarRoute: FlashcardsIdEstudarRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
